//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentorproject.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class school1 : DbContext
    {
        public school1()
            : base("name=school1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Table_category> Table_category { get; set; }
        public virtual DbSet<Table_events> Table_events { get; set; }
        public virtual DbSet<table_student> table_student { get; set; }
        public virtual DbSet<Table_teacher> Table_teacher { get; set; }
        public virtual DbSet<tbl_admins> tbl_admins { get; set; }
        public virtual DbSet<Tbl_img> Tbl_img { get; set; }
        public virtual DbSet<Tbl_course> Tbl_course { get; set; }
        public virtual DbSet<View_courses> View_courses { get; set; }
    }
}
