//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentorproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_course
    {
        public int pkID { get; set; }
        public string title { get; set; }
        public int fkCat { get; set; }
        public string description { get; set; }
        public Nullable<int> fkImg { get; set; }
        public int fkTEACH { get; set; }
        public bool status { get; set; }
    
        public virtual Table_category Table_category { get; set; }
        public virtual Table_teacher Table_teacher { get; set; }
        public virtual Tbl_img Tbl_img { get; set; }
    }
}
