//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentorproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Banners
    {
        public int pkID { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public string Image { get; set; }
        public string Url { get; set; }
        public string ButtonName { get; set; }
        public string ImgAlt { get; set; }
        public string Imgitle { get; set; }
    }
}
