//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentorproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tble_About
    {
        public int pkID { get; set; }
        public string Item { get; set; }
        public string Image { get; set; }
        public string Imageitle { get; set; }
        public string ImageAlt { get; set; }
        public string ButtonName { get; set; }
        public string UrlButtonLink { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
    }
}
