//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentorproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_trainers
    {
        public int pkID { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public int fkImg { get; set; }
        public string address { get; set; }
        public string title { get; set; }
        public string alt { get; set; }
    }
}
