//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace mentorproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_courses
    {
        public int pkID { get; set; }
        public string courseTitle { get; set; }
        public int fkCat { get; set; }
        public string description { get; set; }
        public Nullable<int> fkImg { get; set; }
        public int fkTEACH { get; set; }
        public string category { get; set; }
        public string address { get; set; }
        public string imgTitle { get; set; }
        public string alt { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public bool status { get; set; }
    }
}
